listen: ":8080"
token: "cleanc2-dev-token"
api_token: "cleanc2-api-token"
db: "./data/cleanc2.db"
plugins: "./plugins"
tls_cert: ""
tls_key: ""
client_ca: ""
write_wait: "10s"
pong_wait: "70s"
ping_period: "25s"
